_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 1
                - 5
                - 11
                - 30
                - 41
                - 49
                - 50
                - 53
                - 55
                - 71
                - 98
            "2":
                - 1
                - 5
                - 11
                - 30
                - 41
                - 49
                - 50
                - 53
                - 55
                - 71
                - 98
            "3":
                - 13
                - 16
                - 23
                - 24
                - 55
            "4": 3.11.5
            "5": 0.19.9
            "6": 4.43.1
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 0
dataset:
    value: ""
epochs:
    value: 0
learning_rate:
    value: 0
model_architecture:
    value: ""
num_rounds:
    value: 0
optimizer:
    value: ""
